### ISSUE TITLE
프로필 이미지 변경 시에 로그인 팝업 창이 뜨는 문제

### ISSUE THREAD

**Issue by joohongpark** [innovationacademy-kr/42Swim#103]
### 제목

프로필 이미지 변경 시에 로그인 팝업 창이 뜨는 문제

### 버그에 대한 설명
![image](https://user-images.githubusercontent.com/27172454/148671544-7afe477e-087a-40da-8713-9713434fe65f.png)

프로필 사진 변경 절차
- 이미지 업로드 버튼 클릭하여 파일 선택 후 업로드
- "이미지 업로드를 성공했습니다!" 라는 팝업창이 뜸
- 이후 로그인이 되어있음에도 불구하고 "로그인을 해주세요" 라는 팝업창이 뜸.
- 실제로 로그아웃이 되진 않지만 해당 팝업창이 뜨는 건에 대해 버그라고 판단하여 건의 드립니다.

환경은 맥os 사파리 브라우저입니다.

**Comment by nyeoni** [comment]
이슈 작성 너무 감사드립니다!!
프로필 사진 변경 이슈 수정 완료되었습니다 :)
