### ISSUE TITLE
답변 게시글 preview와 결과가 다른 문제

### ISSUE THREAD

**Issue by Hyoj-Kim** [innovationacademy-kr/42Swim#104]
## 버그에 대한 설명
- https://swim.42seoul.io/detail?id=53 에 답변을 작성했는데, 링크 기능과 인용 기능을 사용해서 preview 확인하고 게시를 눌렀으나, 스타일이 제대로 반영되지 않고 있는 문제가 있습니다.
<img width="799" alt="image" src="https://user-images.githubusercontent.com/76509884/149868855-4d7627da-7b5e-4d5a-b58b-9825abea2e3b.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/76509884/149868872-2d617f10-b3bc-4f0c-a450-0a828c98c5ed.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/76509884/149869062-e54bede8-be71-45e1-b723-74af8548721d.png">

**Comment by Yenowme** [comment]
이슈 남겨주셔서 너무 감사합니다! css 관련 에러로 업데이트 하겠습니다!

**Comment by Yenowme** [comment]
- [x] 인용 스타일 수정
  - 인용 이미지 추가
- [x] 코드 문장 스타일 수정
  - 백그라운드 컬러 변경
  - 폰트컬러 변경
  - 폰트 사이즈 수정
- [ ] 링크 스타일 수정
  - 컬러 변경
