### ISSUE TITLE
글 리스트에서 아이디가 너무 길었을 때 해당 아이디 부분이 미리보기 글을 침범합니다

### ISSUE THREAD

**Issue by yeonwlee** [innovationacademy-kr/42Swim#110]
<img width="991" alt="Screen Shot 2022-02-05 at 4 05 29 PM" src="https://user-images.githubusercontent.com/81205766/152632399-14ed8af8-e672-45c9-a83a-ffc3a54a75ff.png">

**Comment by nyeoni** [comment]
이슈작성 감사합니다!! 바로 수정하도록 하겠습니다 :)
