### ISSUE TITLE
[Hot]로그인 안한 경우 서버 오류 발생

### ISSUE THREAD

**Issue by earthkingman** [innovationacademy-kr/42Swim#27]
### 제목
로그인 안한경우 서버로 무한요청이됨
### 이슈에 대한 설명
![image](https://user-images.githubusercontent.com/48669085/146491991-a890af80-deb6-409e-9330-e00654fd3f40.png)

**Comment by Yenowme** [comment]
### 해결 방법
1. 서버에서 비회원일때 200응답 주고, 프론트에서도 그에 맞게 처리
2. 프론트에서 useSWR 설정 수정
3. 프론트에서 SWR 외에 다른 방법 사용

-> 일단 1번으로 진행
