### ISSUE TITLE
Footer label 너비 수정

### ISSUE THREAD

**Issue by rkskekzzz** [innovationacademy-kr/42Swim#56]
### 버그에 대한 설명

* div class="sc-iqHYmW kHbDpc" 의 width를 380으로 수정하니 해결됩니당!

<img width="1270" alt="스크린샷 2021-12-22 오후 2 38 46" src="https://user-images.githubusercontent.com/57925497/147041443-ae10d0d2-6d04-47d2-b808-3d8ac751f252.png">

**Comment by Yenowme** [comment]
버그 수정 완료했습니다! 레포트 너무 감사드립니다!! 👍
