### ISSUE TITLE
태그 버튼 텍스트 가운데 정렬 이슈

### ISSUE THREAD

**Issue by leekh716** [innovationacademy-kr/42Swim#57]
### 제목
글쓰기 창에서 태그 입력 시 텍스트 가운데 정렬 이슈
### 버그에 대한 설명
- 해당 버그의 스크린샷, 버그가 일어난 상황, 콘솔창을 함께 보여주시면 해결에 큰 도움이 됩니다
![image](https://user-images.githubusercontent.com/76505351/147042064-9be8fdc6-d019-4673-af4c-68506e064032.png)

**Comment by Yenowme** [comment]
버그 레포트 감사합니다 :) 현재 급한 업데이트가 있어 텍스트 정렬은 다음 업데이트에 꼭 반영하도록 하겠습니다!! ㅜㅜ
