### ISSUE TITLE
싫어요 버튼을 눌렀더니 400에러 메세지가 나옵니다.

### ISSUE THREAD

**Issue by jinbekim** [innovationacademy-kr/42Swim#58]
![image](https://user-images.githubusercontent.com/59330110/147043420-3a6de10b-3a90-4b03-a8ed-67c189fa4e68.png)

**Comment by Yenowme** [comment]
랭킹 점수에 영향을 받기 때문에 생긴 버그로, 유저 경험에 좋지 않을 것 같아 수정 예정입니다. 감사합니다!
