### ISSUE TITLE
본문 미리보기 텍스트에 javascript, c 등 본문 중 ```언어 에서 설정한 부분이 보입니다

### ISSUE THREAD

**Issue by leekh716** [innovationacademy-kr/42Swim#59]
### 제목
본문 미리보기 텍스트에 javascript, c 등 본문 중 ```언어 에서 설정한 부분이 보입니다
### 버그에 대한 설명
- 해당 버그의 스크린샷, 버그가 일어난 상황, 콘솔창을 함께 보여주시면 해결에 큰 도움이 됩니다
![image](https://user-images.githubusercontent.com/76505351/147045302-f90eeaff-1f21-4131-8590-6bba21593f46.png)

**Comment by Yenowme** [comment]
regex를 통해 포함되지 않은 항목으로, 업데이트 하겠습니다. 레포트 감사합니다!

**Comment by Yenowme** [comment]
버그 수정 완료했습니다! 레포트 너무 감사드립니다 👍
