### ISSUE TITLE
댓글 수정이 되지 않음.

### ISSUE THREAD

**Issue by jinbekim** [innovationacademy-kr/42Swim#66]
### 제목
- 댓글 수정이 되지 않음.
### 버그에 대한 설명
-  댓글을 달고 1. 2. 같은 번호를 붙이고 싶어서 번호를 붙였는데 수정을 마치면 해당 내용이 적용되는것 같지만, 새로고침을 하면 반영이 되어있지 않음.
- 테스트를 해보니 그냥 수정이 되지 않는것 같습니다.

https://user-images.githubusercontent.com/59330110/147089789-8d020299-e904-4aa5-86c6-7928b8bc60a9.mov

**Comment by jinbekim** [comment]
추가로 이런것도 가능합니다.
<img src="https://user-images.githubusercontent.com/59330110/147090772-38ec6f2e-40fd-41eb-8477-ae0ba1fd6b91.png" width=300>

**Comment by nyeoni** [comment]
현재 원인 파악 되었고 최대한 빠르게 수정하도록 하겠습니다.
제보해주셔서 정말 감사합니다 :)

**Comment by hainho** [comment]
수정하기를 누른 다음에 내용을 수정하고 취소를 눌러도 위와 마찬가지로 수정된 내용이 나왔다가 새로고침하면 수정 전 내용으로 나옵니다
